#!/usr/bin/env node
/**
 * `npx mentonext init` — a small interactive wizard that:
 *   1. asks for your WordPress site's URL
 *   2. checks it's actually reachable via the REST API
 *   3. detects whether Yoast, AIOSEO, or RankMath's headless mode are
 *      already active, by looking at real responses from the site
 *   4. writes a ready-to-import `mentonext.config.ts`
 *
 * Deliberately dependency-free (readline + fetch, both built into Node) —
 * this is a convenience wizard for a zero-config package, so it shouldn't
 * itself pull in a prompts library or an argument parser.
 */
import { createInterface } from 'node:readline/promises';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

async function prompt(question: string, defaultValue?: string): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const suffix = defaultValue ? ` (${defaultValue})` : '';
  const answer = await rl.question(`${question}${suffix}: `);
  rl.close();
  return answer.trim() || defaultValue || '';
}

interface DetectionResult {
  reachable: boolean;
  siteName?: string;
  yoastDetected: boolean;
  aioseoDetected: boolean;
  rankMathHeadlessEnabled: boolean;
  error?: string;
}

/**
 * All detection here is done by asking the live site, never by guessing
 * from the URL or assuming a plugin's default behavior — the RankMath
 * integration in this package exists precisely because an earlier,
 * unverified assumption about RankMath's REST behavior turned out to be
 * wrong. Same discipline applies here: only claim a plugin is active when
 * its actual REST output proves it.
 */
async function detect(baseUrl: string): Promise<DetectionResult> {
  const result: DetectionResult = {
    reachable: false,
    yoastDetected: false,
    aioseoDetected: false,
    rankMathHeadlessEnabled: false,
  };
  const root = baseUrl.replace(/\/$/, '');

  let rootJson: { name?: string; namespaces?: string[] } | undefined;
  try {
    const rootRes = await fetch(`${root}/wp-json/`);
    if (!rootRes.ok) {
      result.error = `WordPress REST API root returned HTTP ${rootRes.status}. Is this a WordPress site, and is the REST API enabled?`;
      return result;
    }
    rootJson = await rootRes.json();
  } catch (err) {
    result.error = `Could not reach ${baseUrl}: ${err instanceof Error ? err.message : String(err)}`;
    return result;
  }

  result.reachable = true;
  result.siteName = rootJson?.name;

  const namespaces = Array.isArray(rootJson?.namespaces) ? rootJson.namespaces : [];
  // RankMath only registers this namespace once its "Headless CMS Support"
  // setting is turned on (the endpoint isn't there otherwise) — so finding
  // it is a direct, verifiable signal that headless mode is already on,
  // not a guess based on the plugin merely being installed.
  result.rankMathHeadlessEnabled = namespaces.includes('rankmath/v1');

  try {
    const postsRes = await fetch(`${root}/wp-json/wp/v2/posts?per_page=1`);
    if (postsRes.ok) {
      const posts = (await postsRes.json()) as Array<Record<string, unknown>>;
      const first = Array.isArray(posts) ? posts[0] : undefined;
      if (first) {
        result.yoastDetected = Boolean(first.yoast_head || first.yoast_head_json);
        result.aioseoDetected = Boolean(first.aioseo_head || first.aioseo_head_json);
      }
    }
  } catch {
    // Non-fatal: SEO plugin detection is a nice-to-have on top of a working
    // base config, not a requirement for the wizard to finish successfully.
  }

  return result;
}

function buildConfigFileContents(baseUrl: string, detection: DetectionResult): string {
  const seoLine = detection.rankMathHeadlessEnabled
    ? `\n  seo: { rankMathHeadless: true }, // detected: RankMath's Headless CMS Support is enabled`
    : '';

  return `// Generated by \`npx mentonext init\`. This is just a plain
// WPAdapterConfig object — edit it freely, re-run the wizard any time, or
// delete it and call createWPClient({ ... }) directly instead.
import type { WPAdapterConfig } from 'mentonext';

const wpConfig: WPAdapterConfig = {
  baseUrl: '${baseUrl}',
  cache: { ttlMs: 60_000, staleWhileRevalidate: true },${seoLine}
};

export default wpConfig;
`;
}

async function runInit(explicitUrl: string | undefined): Promise<void> {
  const baseUrl = explicitUrl ?? (await prompt('WordPress site URL', 'https://example.com'));

  console.log(`\nChecking ${baseUrl} ...`);
  const detection = await detect(baseUrl);

  if (!detection.reachable) {
    console.error(`\n✖ ${detection.error}`);
    console.error('Wrote nothing. Fix the URL and re-run `npx mentonext init`.');
    process.exitCode = 1;
    return;
  }

  console.log(`✔ Reachable${detection.siteName ? ` — "${detection.siteName}"` : ''}`);
  console.log(
    detection.yoastDetected
      ? '✔ Yoast SEO detected — works automatically, no config needed'
      : '  Yoast SEO not detected'
  );
  console.log(
    detection.aioseoDetected
      ? '✔ AIOSEO detected — works automatically, no config needed'
      : '  AIOSEO not detected'
  );
  console.log(
    detection.rankMathHeadlessEnabled
      ? '✔ RankMath "Headless CMS Support" is enabled — seo.rankMathHeadless will be turned on'
      : '  RankMath headless endpoint not found (not installed, or "Headless CMS Support" is off)'
  );

  const outPath = resolve(process.cwd(), 'mentonext.config.ts');
  await writeFile(outPath, buildConfigFileContents(baseUrl, detection), 'utf-8');

  console.log(`\nWrote ${outPath}\n`);
  console.log('Use it like:');
  console.log("  import wpConfig from './mentonext.config';");
  console.log("  import { createWPClient } from 'mentonext';");
  console.log('  const wp = createWPClient(wpConfig);');
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const command = args[0];

  if (command !== 'init') {
    console.log('Usage: npx mentonext init [--url=https://your-wordpress-site.com]');
    process.exitCode = command ? 1 : 0;
    return;
  }

  const urlFlag = args.find((a) => a.startsWith('--url='))?.slice('--url='.length);
  await runInit(urlFlag);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
